// <auto-generated />
namespace beeftechee.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class TrialPropertyUser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TrialPropertyUser));
        
        string IMigrationMetadata.Id
        {
            get { return "201910161140303_TrialPropertyUser"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
